using System;
namespace Kerberos.Sots.GameTriggers
{
	internal enum EventType
	{
		EVNT_GAMEOVER,
		EVNT_TRIGGERTRIGGERED,
		EVNT_COLONYDIED,
		EVNT_PLANETDIED,
		EVNT_FLEETDIED,
		EVNT_SHIPDIED,
		EVNT_ADMIRALDIED,
		EVNT_PLAYERDIED,
		EVNT_ALLIANCEFORMED,
		EVNT_ALLIANCEBROKEN,
		EVNT_GRANDMENACEAPPEARED,
		EVNT_GRANDMENACEDESTROYED,
		EVNT_TREATYBROKEN,
		EVNT_CIVILIANSDIED,
		EVNT_FACTIONENCOUNTERED
	}
}
