using System;
namespace Meebey.SmartIrc4net
{
	public enum ReplyCode
	{
		Null,
		Welcome,
		YourHost,
		Created,
		MyInfo,
		Bounce,
		TraceLink = 200,
		TraceConnecting,
		TraceHandshake,
		TraceUnknown,
		TraceOperator,
		TraceUser,
		TraceServer,
		TraceService,
		TraceNewType,
		TraceClass,
		TraceReconnect,
		StatsLinkInfo,
		StatsCommands,
		EndOfStats = 219,
		UserModeIs = 221,
		ServiceList = 234,
		ServiceListEnd,
		StatsUptime = 242,
		StatsOLine,
		LuserClient = 251,
		LuserOp,
		LuserUnknown,
		LuserChannels,
		LuserMe,
		AdminMe,
		AdminLocation1,
		AdminLocation2,
		AdminEmail,
		TraceLog = 261,
		TraceEnd,
		TryAgain,
		Away = 301,
		UserHost,
		IsOn,
		UnAway = 305,
		NowAway,
		WhoIsUser = 311,
		WhoIsServer,
		WhoIsOperator,
		WhoWasUser,
		EndOfWho,
		WhoIsIdle = 317,
		EndOfWhoIs,
		WhoIsChannels,
		ListStart = 321,
		List,
		ListEnd,
		ChannelModeIs,
		UniqueOpIs,
		NoTopic = 331,
		Topic,
		Inviting = 341,
		Summoning,
		InviteList = 346,
		EndOfInviteList,
		ExceptionList,
		EndOfExceptionList,
		Version = 351,
		WhoReply,
		NamesReply,
		Links = 364,
		EndOfLinks,
		EndOfNames,
		BanList,
		EndOfBanList,
		EndOfWhoWas,
		Info = 371,
		Motd,
		EndOfInfo = 374,
		MotdStart,
		EndOfMotd,
		YouAreOper = 381,
		Rehashing,
		YouAreService,
		Time = 391,
		UsersStart,
		Users,
		EndOfUsers,
		NoUsers,
		ErrorNoSuchNickname = 401,
		ErrorNoSuchServer,
		ErrorNoSuchChannel,
		ErrorCannotSendToChannel,
		ErrorTooManyChannels,
		ErrorWasNoSuchNickname,
		ErrorTooManyTargets,
		ErrorNoSuchService,
		ErrorNoOrigin,
		ErrorNoRecipient = 411,
		ErrorNoTextToSend,
		ErrorNoTopLevel,
		ErrorWildTopLevel,
		ErrorBadMask,
		ErrorUnknownCommand = 421,
		ErrorNoMotd,
		ErrorNoAdminInfo,
		ErrorFileError,
		ErrorNoNicknameGiven = 431,
		ErrorErroneusNickname,
		ErrorNicknameInUse,
		ErrorNicknameCollision = 436,
		ErrorUnavailableResource,
		ErrorUserNotInChannel = 441,
		ErrorNotOnChannel,
		ErrorUserOnChannel,
		ErrorNoLogin,
		ErrorSummonDisabled,
		ErrorUsersDisabled,
		ErrorNotRegistered = 451,
		ErrorNeedMoreParams = 461,
		ErrorAlreadyRegistered,
		ErrorNoPermissionForHost,
		ErrorPasswordMismatch,
		ErrorYouAreBannedCreep,
		ErrorYouWillBeBanned,
		ErrorKeySet,
		ErrorChannelIsFull = 471,
		ErrorUnknownMode,
		ErrorInviteOnlyChannel,
		ErrorBannedFromChannel,
		ErrorBadChannelKey,
		ErrorBadChannelMask,
		ErrorNoChannelModes,
		ErrorBanListFull,
		ErrorNoPrivileges = 481,
		ErrorChannelOpPrivilegesNeeded,
		ErrorCannotKillServer,
		ErrorRestricted,
		ErrorUniqueOpPrivilegesNeeded,
		ErrorNoOperHost = 491,
		ErrorUserModeUnknownFlag = 501,
		ErrorUsersDoNotMatch
	}
}
