using System;
namespace Kerberos.Sots.Steam
{
	public enum AchievementType
	{
		SOTS2_DR_SLEEPLESS,
		SOTS2_STEEL_PUSHER,
		SOTS2_SHIPYARD_SUPERVISOR,
		SOTS2_WE_WILL_CALL_IT,
		SOTS2_HOT_COLD,
		SOTS2_NOTHIN,
		SOTS2_TO_BOLDY_GO,
		SOTS2_ZWORD,
		SOTS2_SWORD_OF_STARS,
		SOTS2_GOT_ROCK,
		SOTS2_STATION,
		SOTS2_INCONVIENIENCE,
		SOTS2_IMITATION,
		SOTS2_WELCOME
	}
}
