using System;
namespace Kerberos.Sots.Steam
{
	public enum EResult
	{
		k_EResultOK = 1,
		k_EResultFail,
		k_EResultNoConnection,
		k_EResultInvalidPassword = 5,
		k_EResultLoggedInElsewhere,
		k_EResultInvalidProtocolVer,
		k_EResultInvalidParam,
		k_EResultFileNotFound,
		k_EResultBusy,
		k_EResultInvalidState,
		k_EResultInvalidName,
		k_EResultInvalidEmail,
		k_EResultDuplicateName,
		k_EResultAccessDenied,
		k_EResultTimeout,
		k_EResultBanned,
		k_EResultAccountNotFound,
		k_EResultInvalidSteamID,
		k_EResultServiceUnavailable,
		k_EResultNotLoggedOn,
		k_EResultPending,
		k_EResultEncryptionFailure,
		k_EResultInsufficientPrivilege,
		k_EResultLimitExceeded,
		k_EResultRevoked,
		k_EResultExpired,
		k_EResultAlreadyRedeemed,
		k_EResultDuplicateRequest,
		k_EResultAlreadyOwned,
		k_EResultIPNotFound,
		k_EResultPersistFailed,
		k_EResultLockingFailed,
		k_EResultLogonSessionReplaced,
		k_EResultConnectFailed,
		k_EResultHandshakeFailed,
		k_EResultIOFailure,
		k_EResultRemoteDisconnect,
		k_EResultShoppingCartNotFound,
		k_EResultBlocked,
		k_EResultIgnored,
		k_EResultNoMatch,
		k_EResultAccountDisabled,
		k_EResultServiceReadOnly,
		k_EResultAccountNotFeatured,
		k_EResultAdministratorOK,
		k_EResultContentVersion,
		k_EResultTryAnotherCM
	}
}
